version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service 
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:452148101414:task-definition/testapp-task:37"
        LoadBalancerInfo:
          ContainerName: "testapp"
          ContainerPort: 80
